---
title: "Untitled"
author: "Kendall Anderson"
date: "10/8/2018"
output: html_document
---

```{r}
library(tidyverse)
library(ggfortify)
library(dplyr)
```

```{r}
raw_data <- read.csv(file="trainingData-release.csv", header=TRUE, sep=",")
```

```{r}
over260 <- raw_data %>%
  filter(Overall_Survival >= 260)
```

```{r}
non_survivors <- over260 %>%
  filter(vital.status == 'D' & Remission_Duration < 260)
```

```{r}
as.tibble(non_survivors)
```

```{r}
deceased <- raw_data %>%
  filter(vital.status == 'D' & Overall_Survival < 260)
```

```{r}
non_survivors <- rbind(deceased, non_survivors)
```

```{r}
survivors <- over260 %>%
  filter(vital.status == 'A')
```

```{r}
as.tibble(survivors)
```

```{r}
as.tibble(non_survivors)
```

Separate out protein data
```{r}
survivors_protein <- survivors %>%
  select(X.Patient_id,
         AKT1,
         AKT1_2_3.pS473,
         BAD,
         BAD.pS112,
         BAD.pS136,
         BAD.pS155,
         GSKA_B,
         GSKA_B.pS21_9,
         KIT,
         NPM1,
         NPM1.3542,
         STAT1,
         STAT1.pY701,
         STAT3,
         STAT3.pS727,
         STAT3.pY705,
         STAT5A_B,
         STAT5A_B.pY694,
         TP53,
         TP53.pS15)
```

```{r}
non_survivors_protein <- non_survivors %>%
    select(X.Patient_id,
         AKT1,
         AKT1_2_3.pS473,
         BAD,
         BAD.pS112,
         BAD.pS136,
         BAD.pS155,
         GSKA_B,
         GSKA_B.pS21_9,
         KIT,
         NPM1,
         NPM1.3542,
         STAT1,
         STAT1.pY701,
         STAT3,
         STAT3.pS727,
         STAT3.pY705,
         STAT5A_B,
         STAT5A_B.pY694,
         TP53,
         TP53.pS15)
```

```{r}
View(non_survivors_protein)
```

### PCA

```{r}
survivors_no_id <- survivors_protein %>%
  select(AKT1,
         AKT1_2_3.pS473,
         BAD,
         BAD.pS112,
         BAD.pS136,
         BAD.pS155,
         GSKA_B,
         GSKA_B.pS21_9,
         KIT,
         NPM1,
         NPM1.3542,
         STAT1,
         STAT1.pY701,
         STAT3,
         STAT3.pS727,
         STAT3.pY705,
         STAT5A_B,
         STAT5A_B.pY694,
         TP53,
         TP53.pS15)
```

```{r}
non_survivors_no_id <- non_survivors_protein %>%
  select(AKT1,
         AKT1_2_3.pS473,
         BAD,
         BAD.pS112,
         BAD.pS136,
         BAD.pS155,
         GSKA_B,
         GSKA_B.pS21_9,
         KIT,
         NPM1,
         NPM1.3542,
         STAT1,
         STAT1.pY701,
         STAT3,
         STAT3.pS727,
         STAT3.pY705,
         STAT5A_B,
         STAT5A_B.pY694,
         TP53,
         TP53.pS15)
```

```{r}
pca_survivors <- prcomp(survivors_no_id)
```

```{r}
pca_non_survivors <- prcomp(non_survivors_no_id)
```

```{r}
autoplot(pca_survivors)
```

```{r}
autoplot(pca_non_survivors)
```

```{r}
combined_prot <- rbind(survivors_protein, non_survivors_protein
                       )
```

```{r}
combined_prot_no_ids <- combined_prot %>%
    select(AKT1,
         AKT1_2_3.pS473,
         BAD,
         BAD.pS112,
         BAD.pS136,
         BAD.pS155,
         GSKA_B,
         GSKA_B.pS21_9,
         KIT,
         NPM1,
         NPM1.3542,
         STAT1,
         STAT1.pY701,
         STAT3,
         STAT3.pS727,
         STAT3.pY705,
         STAT5A_B,
         STAT5A_B.pY694,
         TP53,
         TP53.pS15)
```

```{r}
pca_combined <- prcomp(combined_prot_no_ids)
```

```{r}
autoplot(pca_combined)
```

### Scree Plot

```{r}
layout(matrix(1:2, ncol = 2))  
  screeplot(pca_survivors, type="lines", main="PCA Survivors")
  screeplot(pca_non_survivors, type="lines", main="PCA Non-Survivors")
```

### Silhouette

```{r}
library(cluster)
k.max <- 15
data <- survivors_no_id
sil <- rep(0, k.max)
```

```{r}
# Compute the average silhouette width
# k = 2 to k = 15
for(i in 2:k.max){
  km.res <- kmeans(data, centers = i, nstart = 25)
  ss <- silhouette(km.res$cluster, dist(data))
  sil[i] <- mean(ss[, 3])
}
```

```{r}
# Plot the  average silhouette width
plot(1:k.max, sil, type = "b", pch = 19, 
     frame = FALSE, xlab = "Number of clusters k")
abline(v = which.max(sil), lty = 2)
```


```{r}
library(cluster)
k.max <- 15
data <- non_survivors_no_id
sil <- rep(0, k.max)
```

```{r}
# Compute the average silhouette width
# k = 2 to k = 15
for(i in 2:k.max){
  km.res <- kmeans(data, centers = i, nstart = 25)
  ss <- silhouette(km.res$cluster, dist(data))
  sil[i] <- mean(ss[, 3])
}
```

```{r}
# Plot the  average silhouette width
plot(1:k.max, sil, type = "b", pch = 19, 
     frame = FALSE, xlab = "Number of clusters k")
abline(v = which.max(sil), lty = 2)
```



```{r}
library(cluster)
k.max <- 15
data <- combined_prot_no_ids
sil <- rep(0, k.max)
```

```{r}
# Compute the average silhouette width
# k = 2 to k = 15
for(i in 2:k.max){
  km.res <- kmeans(data, centers = i, nstart = 25)
  ss <- silhouette(km.res$cluster, dist(data))
  sil[i] <- mean(ss[, 3])
}
```

```{r}
# Plot the  average silhouette width
plot(1:k.max, sil, type = "b", pch = 19, 
     frame = FALSE, xlab = "Number of clusters k")
abline(v = which.max(sil), lty = 2)
```

### K-means

```{r}
set.seed(876)
autoplot(kmeans(combined_prot_no_ids, 3), data=combined_prot, label=TRUE)
```

```{r}
k <- kmeans(combined_prot_no_ids, 3)
```

```{r}
#View(k)
```

```{r}
#one <- k$cluster == 1
```

```{r}
#two <- k$cluster == 2
```

```{r}
#three <- k$cluster == 3
```

```{r}
#View(one)
```




